---
all:
  children:
    bootstrap_hosts:
      hosts:
        binturo-staging-bootstrap:
          ansible_host: 1.2.3.4
          ansible_user: changeme
          ansible_port: 22
          ansible_become_exe: /usr/bin/sudo.ws
          environment_name: staging
    hardened_hosts:
      hosts:
        binturo-staging-hardened:
          ansible_host: 1.2.3.4
          ansible_user: "{{ custom_admin_user }}"
          ansible_port: "{{ custom_ssh_port }}"
          ansible_become_exe: /usr/bin/sudo.ws
          environment_name: staging

