---
all:
  children:
    bootstrap_hosts:
      hosts:
        binturo-prod-bootstrap:
          ansible_host: 51.68.151.77
          ansible_user: turing
          ansible_port: 22
          ansible_become_exe: /usr/bin/sudo.ws
          environment_name: prod
    hardened_hosts:
      hosts:
        binturo-prod-hardened:
          ansible_host: 51.68.151.77
          ansible_user: "{{ custom_admin_user }}"
          ansible_port: "{{ custom_ssh_port }}"
          ansible_become_exe: /usr/bin/sudo.ws
          environment_name: prod

