---
all:
  children:
    bootstrap_hosts:
      hosts:
        binturo-dev-bootstrap:
          ansible_host: 10.0.0.110
          ansible_user: gwerko
          ansible_port: 22
          ansible_become_exe: /usr/bin/sudo.ws
          environment_name: dev
    hardened_hosts:
      hosts:
        binturo-dev:
          ansible_host: 10.0.0.110
          ansible_user: "{{ custom_admin_user }}"
          ansible_port: "{{ custom_ssh_port }}"
          ansible_become_exe: /usr/bin/sudo.ws
          environment_name: dev

