---
- name: Reload systemd configuration
  ansible.builtin.systemd_service:
    daemon_reload: true
  listen: Reload systemd and restart backend services

- name: Restart backend services
  ansible.builtin.systemd_service:
    name: "{{ item }}.service"
    state: restarted
  loop:
    - binturo-platform
    - binturo-organizers
  listen: Reload systemd and restart backend services
  when: not ansible_check_mode
