---
- name: Install base system packages
  ansible.builtin.apt:
    name:
      - build-essential
      - ca-certificates
      - curl
      - gnupg
      - uidmap
      - dbus-user-session
      - acl
      - python3
      - python3-venv
      - python3.14-dev
      - python3-debian
      - python3-docker
      - libpq-dev
    state: present
    update_cache: true

- name: Set host timezone
  community.general.timezone:
    name: "{{ binturo_timezone }}"
